config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  root "home#index"

  get "home", to: "home#index"


  resources :blagues, only: [:show, :index, :new, :create, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blague.rb
class Blague < ApplicationRecord

    validates :nom, presence: true
    validates :contenu, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blagues_controller.rb
class BlaguesController < ApplicationController


    def index
        @blagues = Blague.all
    end


    def show
        @blague = Blague.find(params[:id])
    end

    def new
        @blague = Blague.new
    end

    def edit
        @blague = Blague.find(params[:id])
    end


    def create
        @blague = Blague.new(blagues_params)

        if @blague.save
            redirect_to blagues_path
        else 
            render :new
        end

    end

    def update
        @blague = Blague.find(params[:id])
        if @blague.update(blagues_params)
            redirect_to blagues_path
        else 
            render :edit
        end

    end

    def destroy
        @blague = Blague.find(params[:id])
        @blague.destroy
        redirect_to blagues_path

    end

    


    private

    def blagues_params
        params.require(:blague).permit(:nom, :contenu, :auteur)
    end


    

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blagues/edit.html.erb
<h2>Modifier la blague</h2>

<%= form_with model: @blague, local: true do |form| %>

    <% if @blague.errors.any? %>
        <h2>Une erreur est survenue</h2>
        <ul>
            <% @blague.errors.full_messages.each do |msg| %>
                <li><%= msg %> </li>
            <%end%>
        
        </ul>
    <%end%>

    <p>
        <%= form.label :nom %>
        <%= form.text_field :nom%>
    
    </p>
    <p>
        <%= form.label :contenu %>
        <%= form.text_area :contenu%>
    
    </p>
    <p>
        <%= form.label :auteur %>
        <%= form.text_field :auteur%>
    
    </p>

    <p>
        <%= form.submit "Modifier la blague" %>
    </p>

<%end%>

app/views/blagues/index.html.erb
<h2>Toutes les blagues</h2>
<br>
<div><%= link_to "Publier une nouvelle blague", new_blague_path() %></div>
<br>
<% @blagues.each do |blague| %>

    <div>Nom : <%= blague.nom%></div>
    <div>Contenu : <%= blague.contenu%></div>
    <div>Publié par : <%= blague.auteur%></div>
    <div><%= link_to "Voir la blague", blague_path(blague) %></div>
    <div><%= link_to "Modifier la blague", edit_blague_path(blague) %></div>
    <div><%= link_to "Supprimer la blague", blague_path(blague), method: :delete %></div>

    <hr>

<% end %>

app/views/blagues/new.html.erb
<h2>Publier une nouvelle blague</h2>

<%= form_with model: @blague, local: true do |form| %>

    <% if @blague.errors.any? %>
        <h2>Une erreur est survenue</h2>
        <ul>
            <% @blague.errors.full_messages.each do |msg| %>
                <li><%= msg %> </li>
            <%end%>
        
        </ul>
    <%end%>

    <p>
        <%= form.label :nom %>
        <%= form.text_field :nom%>
    
    </p>
    <p>
        <%= form.label :contenu %>
        <%= form.text_area :contenu%>
    
    </p>
    <p>
        <%= form.label :auteur %>
        <%= form.text_field :auteur%>
    
    </p>

    <p>
        <%= form.submit "Publier la blague" %>
    </p>

<%end%>

app/views/blagues/show.html.erb
<h2><%= @blague.nom %> </h2>
<div><%= @blague.contenu %></div>


<div>publié par : <%= @blague.auteur %> </div>

app/views/home/index.html.erb
<div>Hello, je suis sur la page d'accueil :) </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlaguesDroles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>